### PR TITLE
Get the cause of InvocationTargetException when a constructor throws

### LINKED ISSUE #15: Fix java.lang.reflect.InvocationTargetException: null
It would be much better to get the actual exception instead of the exception reflection throws when a method call results in an exception.

### PR DESCRIPTION
**Pull request by Jab125**
Closes #15

### CODE REVIEW

File: languages/java/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java [hunk 1]
```diff
@@ -70,6 +71,7 @@ private void constructMod()
         }
         catch (Throwable e)
         {
+            if (e instanceof InvocationTargetException) e = e.getCause();
```
Comment (Technici4n) [inline languages/java/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java:74]: might be nice to add a comment above to explain that this is done for the error screen

**Comment by Technici4n** [comment]
Note: please resolve the conflict. :wink:

**Review by Technici4n — APPROVED** [review]
